### ISSUE TITLE
loader overrides not working in url(...) notation

### ISSUE THREAD

**Issue by rondonjon** [webpack/css-loader#118]
The URL in the following code in my CSS file:

```
.label {
    background-image:url('!file!label.svg');
}
```

contains a loader prefix as described in the webpack core documentation.

I assume the CSS loader should now locate "label.svg" in the CSS file's directory, pass it through the file-loader, and then replace the url(...) contents accordingly.

Instead, I am getting the following error:

```
Module not found: Error: Cannot resolve module 'label.svg' in /home/user/project/css
```

It works when I remove the loader prefix from the filename and add a global loader definition to the webpack config instead:

```
loaders: [
    {
       test: /label\.svg$/,
       loader: "file"
    },
```

So it seems that the CSS loader doesn't handle loader prefixes properly. Or did I miss anything?

**Comment by sokra** [comment]
Maybe a bit weird but this should work:

`background-image:url('~!file!./label.svg');`

**Comment by rondonjon** [comment]
Works for me, but how come?

**Comment by ConradIrwin** [comment]
I also got bitten by this — why is the ~ necessary?

**Comment by psimyn** [comment]
The `~` makes require calls respect the full path - otherwise anything not starting with a `/` is made relative to current location. Kind of demonstrated by the examples in the [readme](https://github.com/webpack/css-loader#usage) - could maybe use an additional example there.

The alternate/confusing require possibilities needs some more thinking - mentioned in https://github.com/webpack/css-loader/issues/217
