### ISSUE TITLE
 HMR with the css-loader is broken when enable modules

### ISSUE THREAD

**Issue by demohi** [webpack/css-loader#139]
webpack config 
```javascript
{ 
  test: /\.css$/,
  loaders: ['style', 'css?module&localIdentName=[hash:base64:5]']
}
```
css file
```css
body{
  color: black;
}
.test{
  color: red;
}
```
HMR log
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 584
[HMR] Nothing hot updated.
```

package version 

``` javascript
    "css-loader": "^0.18.0",
    "style-loader": "^0.12.3",
    "webpack": "^1.12.0",
    "webpack-dev-server": "^1.10.1"
```

**Comment by sokra** [comment]
It's not broken, HMR behaves different for modules that doesn't export stuff (normal CSS) vs. modules that does export stuff (CSS Modules).

Because CSS Modules export stuff the parent module need to accept the module. See [HMR documentation](http://webpack.github.io/docs/hot-module-replacement.html#how-to-deal-with).

**Comment by demohi** [comment]
Thanks @sokra

**Comment by lydell** [comment]
Probably fixed in https://github.com/webpack-contrib/style-loader/pull/298
