### ISSUE TITLE
Strip final "/" from [path]

### ISSUE THREAD

**Issue by joezimjs** [webpack/css-loader#168]
This is just a suggestion, but I think it'd be nice: when you use `[path]` in `localIdentName`, it always ends with a "-" which replaces the final "/" in the path. Can that final character be stripped out?

**Comment by sokra** [comment]
It's intentional: `[path][name]` should resolve to the original path.

`path/to/file` -> `path="path/to/" name="file"` -> `[path][name]` = `"path/to/file"`
`file` -> `path="" name="file"` -> `[path][name]` = `"file"`

If we would omit the `/` you propably need to use `[path]/[name]` (on *nix) and `[path]\\[name]` (on win), but it would still fail for the case when path is empty:

`path/to/file` -> `path="path/to" name="file"` -> `[path]/[name]` = `"path/to/file"`
`file` -> `path="" name="file"` -> `[path]/[name]` = `"/file"`

**Comment by joezimjs** [comment]
localIdentName is simply used for the class names, as far as I know, so you don't use `[path][name]` in order to get a path to a file, it is just used for identifying where the class comes from. I'd prefer to use my own separator between `[path]` and `[name]`, so the extra hyphen doesn't show up.

E.g. I want to use `[path]_[name]_[local]_[hash:base64:4]`, which I would hope would convert to "path-to_file_className_h4sh" rather than "path-to-_file_className_h4sh". The extra hyphen annoys me. I'll get over it if you truly feel there's merit to keeping the hyphen in there, but I'd be grateful to never see it again.
