### ISSUE TITLE
Using :local or ?modules breaks hot-reload in webpack-dev-server

### ISSUE THREAD

**Issue by snaptopixel** [webpack/css-loader#186]
Hot-reloading works great for css and scss in my project but as soon as I start using `:local` or `?modules` it will only do a full reload which is a real bummer :cry: 

```
[HMR] Cannot apply update. Need to do a full reload!
dev-server.js:19 [HMR] Error: Aborted because 105 is not accepted
    at hotApply (http://localhost:8080/bundle.js:356:31)
    at hotUpdateDownloaded (http://localhost:8080/bundle.js:269:13)
    at hotAddUpdateChunk (http://localhost:8080/bundle.js:249:13)
    at webpackHotUpdateCallback (http://localhost:8080/bundle.js:5:12)
    at http://localhost:8080/0.8521540be4e82d3810b2.hot-update.js:1:1
```

**Comment by snaptopixel** [comment]
**NOTE:** This issue has also been posted in webpack-dev-server here https://github.com/webpack/webpack-dev-server/issues/318

**Comment by dbow** [comment]
I think the comment by @sokra in https://github.com/css-modules/webpack-demo/issues/8#issuecomment-135647584 is relevant:
>CSS Modules behave a bit different to normal styles when hot updated. As they export something, they need to be accepted in the parent module. So you can either do in manually (with module.accept) or if using react combine it with the react-hot-loader. (cc @gaearon)

**Comment by snaptopixel** [comment]
Thanks @dbow I was able to get a decent workflow by using live-reload and extract text plugin.

**Comment by dbow** [comment]
I think this (and the other issue in `webpack-dev-server`) can be closed - it's not a bug with css-loader or the webpack-dev-server. As @sokra points out in https://github.com/webpack/css-loader/issues/139#issuecomment-143034812, you need to get your components re-rendering because the CSS module will have a new export. The two solutions mentioned above are the two ways to do that. Ended up going with react HMR transform since that seemed relatively simple: https://github.com/dbow/futureplate/commit/bfff74b8e64f2d6fff3a51b3f0188077ce3793ab.

**Comment by export-mike** [comment]
@dbow hi so is this now possible by using HMR transform?

**Comment by dbow** [comment]
@export-mike yup, I was able to get it working with that!

**Comment by scriby** [comment]
I was able to get this working using react-hot-loader. The project I'm working on is in typescript, and https://github.com/wmaurer/react-hot-boilerplate-ts was a nice small example of how to combine the two.
