### ISSUE TITLE
How can i set the discardComments.removeAll config option for cssnano?

### ISSUE THREAD

**Issue by delijah** [webpack/css-loader#341]
cssnano supports the following config option:

```
{
    discardComments: {
        removeAll: true
    }
}
```

How can i pass this config option through css-loader to cssnano?

http://cssnano.co/optimisations/

**Comment by CookPete** [comment]
I figured this out through trial and error because it doesn't seem to be documented at all. Basically, the options given to cssnano start off as simply [the query that you set for the loader](https://github.com/webpack/css-loader/blob/22f6621a175e858bb604f5ea19f9860982305f16/lib/processCss.js#L181), so this worked for me:

```js
{
  test: /\.css$/,
  loader: 'css?{discardComments:{removeAll:true}}'
}
```

**Comment by viko16** [comment]
@CookPete 

It worked in Webpack@1, but not work in Webpack@2.1.0-beta.25

My code:

```javascript
{
  test: /\.styl$/,
  loader: 'style!css?{discardComments:{removeAll:true}}!stylus'
}
```

**Comment by CookPete** [comment]
@viko16 I don't know how webpack 2 deals with loader queries now, but it may be worth trying the actual `query` config option rather than inlining the JSON structure in the loader string? More info in https://github.com/webpack/webpack/issues/482

For your example, something like this (complete guess):

```js
module: {
  loaders: [{
    test: /\.styl$/,
    loaders: [
      {
        loader: 'style'
      },
      {
        loader: 'css',
        query: {
          discardComments: {
            removeAll: true
          }
        }
      },
      {
        loader: 'stylus'
      }
    ]
  }]
}
```

**Comment by viko16** [comment]
OMG, I found that I just forgot to add parameters '-p': 😂

```bash
# before
cross-env NODE_ENV=production webpack
# after √
cross-env NODE_ENV=production webpack -p
```

Then everything is all right!!!!!!

**On the other hand, both "inline query string" and "JSON structure" are effective. Thank you for your help. :+1: @CookPete **

**Comment by delijah** [comment]
Awesome, works like a charm 👍

**Comment by JounQin** [comment]
What if I'm using `webpack`'s js API what means I can't pass the param `-p`?
